### ISSUE TITLE
watchers not working in V2.5

### ISSUE THREAD

**Issue by fabu-gharbieh** [ryangjchandler/spruce#105]
In V2.5 it seems that watchers won't get triggert anymore. The data is being saved correctly to the store, but the watchers are not reacting. When I downgrade back to V2.3 everything is working fine.

Here's sample code:

```
// create the store
Spruce.store('data', []);

// watch for changes
Spruce.watch('data', value => {
  console.log(value);
});

// set new values
Spruce.reset('data', ['value1', 'value2']);
```

**Comment by ryangjchandler** [comment]
I haven't actually tried, but calling `reset` won't run watchers I don't think.

**Comment by fabu-gharbieh** [comment]
Ok, I understand. It seems like reset doesn't trigger watch anymore. It used to do it in V2.3. I will try to use Setters instead. Thanks

**Comment by ryangjchandler** [comment]
> Ok, I understand. It seems like reset doesn't trigger watch anymore. It used to do it in V2.3. I will try to use Setters instead. Thanks

That's a breaking change on my part, `reset` was never supposed to trigger watchers. Sorry for the trouble! I can release a patch tomorrow that reverts this behaviour!

**Comment by breadthe** [comment]
I noticed some functionality recently broke on one of my apps without touching anything.

It's partially my bad because I was pulling from the CDN like so `<script src="https://cdn.jsdelivr.net/npm/@ryangjchandler/spruce@2.x.x/dist/spruce.umd.js"></script>`.

I tested with `<script src="https://cdn.jsdelivr.net/npm/@ryangjchandler/spruce@2.5.x/dist/spruce.umd.js"></script>` - still broken. Then I changed to `<script src="https://cdn.jsdelivr.net/npm/@ryangjchandler/spruce@2.3.x/dist/spruce.umd.js"></script>` - this one works.

**Comment by ryangjchandler** [comment]
@breadthe What functionality exactly?

**Comment by ryangjchandler** [comment]
@fabu-gharbieh @breadthe Sorry for the delay on this one, been a bit busy! Please try upgrading to v2.5.1 which includes a patch for this problem.

If you're interested in the solution, you can find the changes and brief explanation here, #106.

**Comment by ryangjchandler** [comment]
@heyfadii I've had to revert the changes from #106 as it had a knockon effect on other features. I'll be releasing v2.5.2 later on with this reverted change, so please be aware that your "problem" will still exist.

I should make it clear that my original intention with `Spruce.reset()` was to make it a **hard reset**, meaning watchers, state, etc will be lost.

If you think this feature is still something you need, let me know below.

@breadthe What problems were you experiencing with v2.5.0?
