### ISSUE TITLE
Love your library, but how do you unwatch?

### ISSUE THREAD

**Issue by MarcGodard** [ryangjchandler/spruce#109]
I am building a web app without using any frameworks, and your library is a great help. Just wondering if there is a way to unwatch?

**Comment by ryangjchandler** [comment]
There's not actually a method for this at the moment. I'll add this in and make a release.

**Comment by MarcGodard** [comment]
Can I also recommend a method that gets all the watchers for a specific variable?

**Comment by ryangjchandler** [comment]
> Can I also recommend a method that gets all the watchers for a specific variable?

You sure can!
