### ISSUE TITLE
Watching persistent store results in an error

### ISSUE THREAD

**Issue by mikestempien** [ryangjchandler/spruce#115]
Appears that `>=2.4.0` breaks something with persistent object store + watch combo

```
Spruce.store('test', {
    enabled: false,
}, true);

Spruce.watch('test.enabled', function(enabled) {
    //..
});
```

Results in:

`Uncaught TypeError: Cannot read property 'has' of undefined at Object.watch (spruce.umd.js:1)`

**Comment by ryangjchandler** [comment]
@mikestempien Have you tried upgrading to latest version?

**Comment by ryangjchandler** [comment]
@mikestempien Have you got a CodePen or something similar that can reproduce this problem too. I'm not able to get this error using the code you provided above (it did unveil another issue though, so thanks).

**Comment by mikestempien** [comment]
@ryangjchandler yes, `2.5.2` today. You may need to throw alpinejs in.  
See https://jsfiddle.net/y7ajfwgh/

**Comment by ryangjchandler** [comment]
@mikestempien Here is a JSFiddle that works: https://jsfiddle.net/qh0wxe4u/1/

**Comment by ryangjchandler** [comment]
@mikestempien Comparing our 2 examples, the only difference between them is the order the `<script>` tags are included.

**Comment by ryangjchandler** [comment]
@mikestempien I've tested with the changes made in #116 and it fixed the problem. Please upgrade to v2.5.3 https://github.com/ryangjchandler/spruce/releases/tag/v2.5.3

**Comment by mikestempien** [comment]
Confirming, it works with `2.5.3`. Thanks for looking into it, really appreciate it.

**Comment by ryangjchandler** [comment]
> Confirming, it works with `2.5.3`. Thanks for looking into it, really appreciate it.

No worries, that's what I'm here for!
