### ISSUE TITLE
Error when watching by dot notation

### ISSUE THREAD

**Issue by MarcGodard** [ryangjchandler/spruce#121]
Works: `Spruce.watch('color', () => {})`

Errors: `Spruce.watch('color.dark', () => {})`

**Comment by ryangjchandler** [comment]
@MarcGodard What is the error?

**Comment by ryangjchandler** [comment]
@MarcGodard I've got a CodePen here with a dot-notated watcher and it all seems to be working fine: https://codepen.io/ryangjchandler/pen/ZEpNPjK

**Comment by MarcGodard** [comment]
I get the error `Uncaught TypeError: e is undefined`
When I change it to the following it all works:

```javascript
Spruce.watch('color.dark', function (value) {
      if (value.dark) {
      }
})
```

Will explore this error in detail later this week.

**Comment by ryangjchandler** [comment]
@MarcGodard Did you get any further with this?

**Comment by MarcGodard** [comment]
Not yet, sorry this is for a fun project. I will close for now but we can reopen if and when i run into this again.
