### ISSUE TITLE
Add a License?

### ISSUE THREAD

**Issue by jacksegal** [ryangjchandler/spruce#13]
hey @ryangjchandler - looks great!

i couldn't see a license for this project so thought i'd let you know about this site: https://choosealicense.com/ - they also have a section on what "not having a license" means: https://choosealicense.com/no-permission/

someone once sent me those links for my first (and only) open source project, so thought i'd do the same for you - however if you're happy without a license then feel free to ignore :-)

for reference, alpine uses MIT: https://github.com/alpinejs/alpine#license

if you do decide to add a license you can just add a copy of the license to the root of the project (`LICENSE.md` / `LICENSE.txt` / etc.) and then add a small section to the end of the README (see alpine).

thanks,
jack

**Comment by ryangjchandler** [comment]
Hey @jacksegal ,

Thansk for opening the issue. I'm aware the LICENSE is missing, it's actually MIT licensed in the package.json, I just forgot to put the Markdown file in the repo.

Feel free to make a PR for the LICENSE.md file, it'll give you a "contributor" badge on the repo. If not, I'll do it later on.

Thanks again! :)
