### ISSUE TITLE
[Spruce] You have already initialised a persisted store. Changing the driver may cause issues.

### ISSUE THREAD

**Issue by Pixney-William** [ryangjchandler/spruce#130]
To start with, i use bundlers.

I then import spruce and set it to use Session storage:
```
import Spruce from '@ryangjchandler/spruce'
Spruce.persistUsing(window.sessionStorage)
```

After that i set my stores. However, doing it this way a warning message shows up in the browser:
`[Spruce] You have already initialised a persisted store. Changing the driver may cause issues.`

Should i ignore the warning of am i setting the Storage wrong?

**Comment by ryangjchandler** [comment]
@Pixney-William Are you calling `Spruce.store()` before setting `Spruce.persistUsing`?

**Comment by Pixney-William** [comment]
Sorry for wasting your time. I missed that Spruce was set to the window automatically so it was my own fault duplicating things :(
