### ISSUE TITLE
Conditional CSS with persistence

### ISSUE THREAD

**Issue by phijma** [ryangjchandler/spruce#136]
This is maybe more of a question than a bug report.

Idea:
`<div :class="{ 'max-w-7xl': !$store.isFullScreen }"></div>`

I store the value of a `isFullScreen` variable with Spruce. Now I'd like it to store the users preference so I'm using the persistence option.

But whenever I load any page, you can see the page flash a little (going from full screen to non-full screen). Because it needs to load the store I guess.

Any idea how to make that "flashy" effect disappear?

**Comment by phijma** [comment]
Adding `<body x-data x-cloak>` seems to solve it... weird? Guess it's more an alpine thingy

**Comment by ryangjchandler** [comment]
> Adding `<body x-data x-cloak>` seems to solve it... weird? Guess it's more an alpine thingy

Yeah, that's more of an Alpine thing. Spruce shouldn't have to concern itself with anything apart from state management.

Be careful using `x-data` on the `<body>` though, since Alpine will have to walk the entire DOM tree of the `<body>` which can have a performance hit on larger pages.

**Comment by phijma** [comment]
Thanks!

(Yeah, not gonna use that solution :P)
