### ISSUE TITLE
Support persistence drivers at store level

### ISSUE THREAD

**Issue by ntrrg** [ryangjchandler/spruce#142]
Hi! not sure if this would be hard to implement, but what do you think about setting a persistence driver per store?

```js
Spruce.store('player', { name: "Thrall", battles: 11, victories: 6 }, window.localStorage)
Spruce.store('battleGround', { name: "Warsong Gulch", alliance: [...], horde: [...] }, window.sessionStorage)
```

**Comment by ryangjchandler** [comment]
@ntrrg Not a bad idea - I'll investigate this weekend!

**Comment by rehhouari** [comment]
I second this

**Comment by ryangjchandler** [comment]
Let me have a look at this one right now.

**Comment by ryangjchandler** [comment]
@rehhouari @ntrrg Please see the PR above. I'll be merging and releasing soon.

**Comment by ntrrg** [comment]
Great! thanks for your work
