### ISSUE TITLE
Documentation website  Error 1014 - CNAME Cross-User Banned

### ISSUE THREAD

**Issue by iskrisis** [ryangjchandler/spruce#143]
I am getting this error when i go to docs website
![CleanShot 2021-03-31 at 11 49 29](https://user-images.githubusercontent.com/4954323/113125719-3077e900-9217-11eb-95aa-b9f0474dc83f.png)

I don't think its my fault?

Thank you!
Cheers

**Comment by ryangjchandler** [comment]
@iskrisis I'm aware of the problem. GitBook has a problem with my DNS, despite the fact that I followed their own instructions twice now.

**Comment by iskrisis** [comment]
Thats unfortunate. 
Well i am atleast sending some good energy

![b94](https://user-images.githubusercontent.com/4954323/113127204-c6f8da00-9218-11eb-833f-00258e149d55.jpg)

Cheers
