### ISSUE TITLE
Not able to use Spruce with imports / without cdn

### ISSUE THREAD

**Issue by mansoorkhan96** [ryangjchandler/spruce#153]
I am trying to use spruce with alpine.js for a chrome extension. I am loading spruce from node modules in a build file named popup.js
This is what I am doing.
```
// popup.js
import Spruce from "@ryangjchandler/spruce"
import Alpine from "alpinejs";

window.Spruce.store('modal', {
    open: 'login',
}, true);

window.Alpine = Alpine;

Alpine.start();

console.log(Spruce.store('modal'))
```

The HTML is the same as from docs.
```
<div x-data>
      <div x-show="$store.modal.open === 'login'">
        <p>
          This "login" modal isn't built with a11y in mind, don't actually use
          it
        </p>
      </div>
    </div>

    <div x-data>
      <div x-show="$store.modal.open === 'register'">
        <p>
          This "register" modal isn't built with a11y in mind, don't actually
          use it
        </p>
      </div>
    </div>

    <div x-data>
      <select x-model="$store.modal.open">
        <option value="login" selected>login</option>
        <option value="register">register</option>
      </select>
    </div>

    <script defer type="module" src="popup.js"></script>
```

I am getting the following error:
![image](https://user-images.githubusercontent.com/51432274/147812897-e09c1e92-a84d-4cdb-8bff-5ed3b56d4aed.png)

**Comment by ryangjchandler** [comment]
@mansoorkhan96 Unfortunately, Spruce doesn't receive any updates anymore and I'd highly recommend using Alpine 3.x and `Alpine.store()`.

**Comment by mansoorkhan96** [comment]
@ryangjchandler ah, ok great. I just had a look. I am wondering if it supports persisting?

**Comment by mansoorkhan96** [comment]
I could persist data with spruce by giving the third param to `store()` seems like it's missing from alpine.

**Comment by ryangjchandler** [comment]
You can use Alpine.persist I believe.
