### ISSUE TITLE
Implement global `$store` variable

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/spruce#17]
Currently you have to add the `x-subscribe` directive to your root component element to access the `$store` variable.

Since Alpine can read variables from the `window` scope, it would be possible to also remove the need for `x-subscribe` and instead add `window.$store`.

```html
<div x-data>
    <span x-text="$store.application.name"></span>
</div>
```

I think to begin with, this would be an "opt-in" feature. Maybe add a `Spruce.enabledGlobalStoreVariable` to the core object and let the developer set it to `true`. Would be great to get some other thoughts on this too, @HugoDF?

**Comment by ryangjchandler** [comment]
In terms of the overhead of this approach, we'd need to either:

1. Build up a dependency graph in memory of each dependent component. This could be done using the `get` trap on the Proxy. I'd prefer this method personally, since it wouldn't be too difficult I don't think.

2. Find a way to force render each component through Alpine. This won't be very optimised though...

**Comment by HugoDF** [comment]
Sounds reasonable

How would you set the Boolean? `Spruce.config({ globalStore: true })` is the more flexible API

**Comment by ryangjchandler** [comment]
> Sounds reasonable
> 
> How would you set the Boolean? `Spruce.config({ globalStore: true })` is the more flexible API

Yeah, either a `config` function or a single `Spruce.variableName = true`. The Config API would make more sense for future options too.
