### ISSUE TITLE
Add polyfills for IE11 support

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/spruce#18]
Need to add some polyfills so that IE11 is supported. I'm going to see if the polyfills Alpine provides will work with Spruce out of the box, so we don't have to bundle them again.

**Comment by ryangjchandler** [comment]
I'm debating whether or not to even support IE11 - the current build doesn't and I haven't even had too many requests for support, so it seems like more hassle than it's worth at the moment.

**Comment by ryangjchandler** [comment]
Taking the conscious decision to **not** support Internet Explorer. Nobody has complained about it and it's probably a good step to take.

**Comment by bjoern-flagbit** [comment]
Nice. I would need this now. 

Maybe I just create the dist locally or you wanna provide this also like with your releases like alpinejs is doing?

**Comment by bjoern-flagbit** [comment]
You need to add core-js like:
`yarn add core-js --dev`

Edit **babel.config.js** file to this
```
module.exports = {
    presets: [
        [
            '@babel/preset-env',
            {
                corejs: {
                    version: "3",
                    proposals: true
                },
                useBuiltIns: 'usage',
                targets: {
                    browsers: [
                        "edge >= 16",
                        "safari >= 9",
                        "firefox >= 57",
                        "ie >= 11",
                        "ios >= 9",
                        "chrome >= 49"
                    ]
                }
            }
        ],
    ],
};
```
And then run:
`yarn build`

**Comment by Wurielle** [comment]
It would be nice to have an alternative solution for at least IE11. 
If anyone managed to solve this issue with their module bundler, feel free to share every steps.
The answer above didn't work for me and I tried to hack the source files without success either..
