### ISSUE TITLE
Automate release cycle with GitHub Actions

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/spruce#19]
I'd like to make use of GitHub Actions and automate the release process.

This would include:

* Triggering workflow on GitHub tag / release.
* Running all tests.
* Building `/dist` files.
* Pushing `/dist` to tag / release.
* Uploading distribution artifact to release.
* Publishing to NPM.

**Comment by SimoTod** [comment]
Hi @ryangjchandler 
do you need help with this task? I've got a working workflow doing pretty much this but let me know if you want to experiment.

**Comment by ryangjchandler** [comment]
> Hi @ryangjchandler 
> 
> do you need help with this task? I've got a working workflow doing pretty much this but let me know if you want to experiment.

Hey Simone! Feel free to make a PR, this was one of the last things I wanted to do for v1, but if you've got a workflow already I'd love to see it. Appreciate it! :)

**Comment by SimoTod** [comment]
cool, i'll send you a PR. It should work but feel free to tweak it if there something that doesn't apply to Spruce. You'll see in a minute but the biggest limitation is that it expects you to publish from master since it pushes everything back to that branch.
