### ISSUE TITLE
Create a "getter" for stores

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/spruce#24]
I'm thinking it makes sense to provide a "getter" method so that stores can be used outside of your Alpine components.

My initial thoughts are to use the existing `Spruce.store()` method, and check to see if the second argument is empty / undefined / null.

If it is, and the first argument is a valid store, then return it.

Thoughts? cc/ @HugoDF

**Comment by HugoDF** [comment]
That API looks ok to me 👍 

Watch out that tests cover both the `store('hello')` and `stores.hello` cases seems clean enough

**Comment by ryangjchandler** [comment]
> That API looks ok to me 👍
> 
> Watch out that tests cover both the `store('hello')` and `stores.hello` cases, otherwise seems clean enough

Ah yeah I just replaced all `stores.` with `store()`.
