### ISSUE TITLE
Add a "Quick Start" section

### ISSUE THREAD

**Issue by HugoDF** [ryangjchandler/spruce#26]
👋 I was just creating a Spruce example for a post and I noticed there isn't a "here's some sample code you can copy paste to make sure things are working" anywhere in the README.

In Alpine that's things like the dropdown.

In Spruce it would be nice to have a couple of components and a store.

This is what I came up with (see the [CodePen](https://codepen.io/hugodf/pen/dyYJXEa)):

```html
<div x-data="{}" x-subscribe>
    <div x-show="$store.modal.open === 'login'">
    <p>
      This "login" modal isn't built with a11y in mind, don't actually use it
    </p>
    </div>
</div>
<div x-data="{}" x-subscribe>
    <div x-show="$store.modal.open === 'register'">
    <p>
      This "register" modal isn't built with a11y in mind, don't actually use it
    </p>
    </div>
</div>
<div x-data="{}" x-subscribe>
  <select x-model="$store.modal.open">
    <option value="login" selected>login</option>
    <option value="register">register</option>
  </select>
</div>
<script>
  Spruce.store('modal', {
    open: 'login',
  });
</script>
```

**Comment by gilbert** [comment]
For the record: The inline `<script>` tag approach may not work if you're including Alpine in a [deferred/async script](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer). A nice alternative that I think always works is to put your store declaration in an `x-init`:

```html
<div x-data="{}" x-init="Spruce.store('model', { open: 'login' })">
  <div x-show="$store.modal.open === 'login'">...</div>
</div>
```

**Comment by ryangjchandler** [comment]
True. I've actually had a couple of people mention this and I'm looking into ways of changing the internals so that Alpine can be included anywhere, as well as Spruce.
