### ISSUE TITLE
[Improvement] Optional attributes to be more quiet

### ISSUE THREAD

**Issue by OwenMelbz** [ryangjchandler/spruce#3]
Hey, good work so far!

Just trying out some common use cases that cause complications in other systems with things that can cause aggravation!

I've got 1 issue that would improve the developer experience and that is the idea of optional attributes to allow avoiding conditional code everywhere.

This is a very dumbed down example, but imagine your user data is stored on an API and you need to fetch the users data before displaying it, being able to reference this data as optional so it doesn't throw an error allowing people to do things like `x-text="$store.accounts.user.name || 'Guest'"`

```js
Spruce.store('accounts', {
    user: null
});

const { data } = await axios.get('/me');
Spruce.stores.accounts.user = data;
```

Currently that will throw an error saying something like `name doesn't exist on null`

It wouldn't be very "nice" to have the user define all the fields that could be returned by the API endpoint, so making sure these are handled more quietly would be nice!

You can see the console errors in this demo: https://codepen.io/owenmelbz/pen/bGVWaWZ

---------

Secondly, just a quick one for caution, noticed in the source code https://github.com/ryangjchandler/spruce/blob/master/src/index.js#L12 you've got

```js
document.querySelectorAll('[x-subscribe]').forEach(el => {
```

*ideally* to support IE, querySelectorAll doesn't actually return an Array, it returns a NodeList which doesn't have a `forEach` method on it.

Super simple fix is to wrap it in an Array method e.g.

```js
Array.from(document.querySelectorAll('[x-subscribe]')).forEach(el => {
```

Instant fix for everybody without hassle :D I know there will be other errors like the Proxies but least this one is super easy to fix with almost zero extra overhead!

Keep up the good work!

**Comment by ryangjchandler** [comment]
Hey @OwenMelbz , thanks for giving the package a try! Both of these are on my list already, I'm aiming for full IE11 support in v1.x, I still need to write tests for the current version 😅

Good shout with the optional attributes and the current errors that occur. What would you suggest returning as a default value, undefined is normally a good choice...

**Comment by OwenMelbz** [comment]
well... that’s a tricky one!!!

Laravel opts for the null object pattern, so fans of that would like null.

technically it would be correct to be undefined as it’s well... not 😂 

it’s nicer to write `variable === null` than `typeof variable === “undefined”`

but also if people were to do something like.....

`$store.user.name.toLowerCase()` then undefined and null will throw errors. so i’m that instance it’s nicer to return an empty string, that way they can do simple truthy tests on it.

so i’d say there’s 3 options to pick from...

i’d probably lean towards an empty string or null as it will lead to more simple code for the developers to work with, even though it isn’t technically correct??

if you can’t decide, maybe consider a Spruce options api e.g

```
Spruce.options({
    undefinedValue: undefined, // null “” undefined etc...
})
```

options api allows more flexibility down the line?

**Comment by ryangjchandler** [comment]
Yeah I like the concept of an options API too... clever thinking. I'd lean for the undefined approach maybe, and leave the rest down to the developer (if they use method calls on undefined etc).

**Comment by devcircus** [comment]
seems like the null situation is something that's inherent in the language itself which shows up in Vue, React, Alpine, etc. etc. Not sure I'd want those errors suppressed. One way to avoid the conditionals is to be more specific when defining the object. So instead of ```{ user: null }```, use:
```js
{
    user: {
        name: '',
        age: '',
    }
}
```
But I guess if it can be handled in a universal way that satisfies all possible dev preferences and edge cases, go for it.

**Comment by OwenMelbz** [comment]
> seems like the null situation is something that's inherent in the language itself which shows up in Vue, React, Alpine, etc. etc. Not sure I'd want those errors suppressed. One way to avoid the conditionals is to be more specific when defining the object. So instead of ```{ user: null }```, use:
> 
> ```js
> 
> {
> 
>     user: {
> 
>         name: '',
> 
>         age: '',
> 
>     }
> 
> }
> 
> ```
> 
> But I guess if it can be handled in a universal way that satisfies all possible dev preferences and edge cases, go for it.

the reason didn’t want to go down this route was because imagine if you have say 20 properties on 5 different stores will get massive and unwieldily, or using GraphQL where the results are dynamic, pretty grim having to write these all out from an “experience” point of view

**Comment by ryangjchandler** [comment]
I'm going to close this issue now and leave this one down to the developer to handle. It's more a language problem than something that should be handled by the library, Alpine would have the same response too.
