### ISSUE TITLE
Spruce.watch is not triggered with Spruce.reset

### ISSUE THREAD

**Issue by chapmanjacobd** [ryangjchandler/spruce#36]
I think the current behavior is fine but it might be nice to add an option object/parameter to Spruce.watch which would switch between no trigger and trigger after reset behaviors

**Comment by chapmanjacobd** [comment]
maybe this would be difficult to program correctly. 

an alternative option might be to have the ability to externally trigger all "watchers" so that they will refresh. This should all be optional and not the default because I fear it might somehow create a watch loop for some people

**Comment by ryangjchandler** [comment]
@chapmanjacobd - I'm not sure whether watchers should be triggered at all when resetting. The whole point of that method is that it's resetting the state, not pushing a change.

**Comment by chapmanjacobd** [comment]
Is there a method to get a list of the watchers and their saved functions? That would solve my issue

**Comment by HugoDF** [comment]
If you look at the `Spruce` object, it has a `subscribers` property (https://github.com/ryangjchandler/spruce/blob/master/src/index.js#L14) and also a `updateSubscribers` (https://github.com/ryangjchandler/spruce/blob/master/src/index.js#L69)
