### ISSUE TITLE
Cannot use a function from a store for an event

### ISSUE THREAD

**Issue by arthurwhite** [ryangjchandler/spruce#37]
```html
<script>
    Spruce.store("user", {
        submit() { alert("OK"); }
    });
</script>

<form x-data="{}" x-subscribe @submit.prevent="$store.user.submit">
    <input type="submit">
</form>
```

This does nothing.
It's like the `$store` variable is not available for event handlers.

See: https://codepen.io/arthurwhite/pen/JjGWgda

**Comment by HugoDF** [comment]
@arthurwhite with spruce you need to actually call the function I believe so `@submit.prevent="$store.user.submit()"`

**Comment by ryangjchandler** [comment]
Yeah, @HugoDF is right - you need to actually invoke the function.

**Comment by arthurwhite** [comment]
Thanks!
