### ISSUE TITLE
Spruce is not defined

### ISSUE THREAD

**Issue by chapmanjacobd** [ryangjchandler/spruce#38]
I'm trying to use this in a new project without a bundler:

tee index.html
```html
<head>
    <script src="https://cdn.jsdelivr.net/gh/ryangjchandler/spruce@0.6.1/dist/spruce.umd.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.4.1/dist/alpine.min.js" defer></script>
</head>
<body>

    <div x-data="{}" x-subscribe>

        <label for="links">Links:</label>
        <textarea id="links" x-model="$store.settings.links" /></textarea>
    </div>


    <script>
        Spruce.store('settings', {})
    </script>
</body>
```

(ctrl+d)

but I get "Spruce is not defined"

**Comment by chapmanjacobd** [comment]
I can wrap the `Spruce.store('settings', {})` in a `window.onload` but then Alpine will run first and complain about that `$store.settings` is not defined

**Comment by chapmanjacobd** [comment]
ahhh removing `defer` from alpine.js (like [the example](https://github.com/ryangjchandler/spruce/blob/master/examples/index.html)) actually made it work

**Comment by ryangjchandler** [comment]
Yeah, defer is a funny attribute. The docs need updating because I'd actually recommend putting both script tags at the end of the body tag (before your inline script tag).

**Comment by rizkhal** [comment]
thanks for this great package

i use alpine3 and when i remove the `defer` tag, i have any error because alpine need `defer` with livewire, any solution?

**Comment by chapmanjacobd** [comment]
Spruce [only supports alpine2](https://github.com/ryangjchandler/spruce#-spruce)

> With the release of Alpine 3.x, Spruce has been replaced with a first-party $store helper, as well as Alpine.store. This package will continue to support Alpine 2.x, but only with security releases. I want thank everyone who has used and supported this packages development over the last couple of years, it really does mean a lot. ❤️
