### ISSUE TITLE
Add shorthand access to store namespaces

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/spruce#4]
Nice suggestion from @breadthe on Twitter:

https://twitter.com/brbcoding/status/1254489574274973696?s=20

Would add support for accessing `Spruce.store('application', {})`... using `$application` instead of `$store.application`

**Comment by devcircus** [comment]
Instead of using x-subscribe, you can customize the variable however you want in x-init. So if you have:
```js
store.spruce('application', { name: '' });
```
Use the following to access with ```app```:
```html
<div x-data x-init="app = spruce.subscribe($el).application">
```
Then, in your component, you can use, for example, ```x-model="app.name"``` instead of ```x-model="$store.application.name```.

**Comment by ryangjchandler** [comment]
Yeah that's one way of doing it currently.

**Comment by ryangjchandler** [comment]
Hi guys, I'm going to close this issue now and leave it behind. I don't think this it worth it currently and if it's that much of a problem, please open up another issue.
