### ISSUE TITLE
Remove namespace / scope from package

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/spruce#43]
I want to remove the `@ryangjchandler` from the package name and instead rename it so `spruce` or `spruce.js`.

**Comment by HugoDF** [comment]
`sprucejs` seems available

**Comment by ryangjchandler** [comment]
> 
> 
> `sprucejs` seems available

Yeah, I like that one. It's nice to have my name in it, but it also feels like a bit "meh, not reliable because it's some random guy" sort of thing haha.

**Comment by HugoDF** [comment]
Also: kinda long to type out if anyone ever wants to recommend it to someone else 😄
