### ISSUE TITLE
$store is not defined

### ISSUE THREAD

**Issue by ammezie** [ryangjchandler/spruce#50]
When I try calling `$store` inside a component's method, I get 

```
Uncaught ReferenceError: $store is not defined

at Proxy.addTodo...
```

where `addTodo` is the name of the method.

But when I use it inline in the template everything works as expected.

**Comment by ryangjchandler** [comment]
Inside of a function, you need to use `this.$store`.

**Comment by ammezie** [comment]
Oh! Thanks!
