### ISSUE TITLE
Implement history / change tracking

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/spruce#51]

**Comment by jeremyswann** [comment]
is this the same principle as persistence, that would be a sick feature

**Comment by ryangjchandler** [comment]
@jeremyswann - I've got plans to add some persistence in v2, it would be an opt-in feature. The API would look something like:

```js
Spruce.store('application', {
    name: 'Example',
}, true)
```

Where the third argument defaults to `false`.

Is this something you'd be interested in?

**Comment by jeremyswann** [comment]
I would find this highly useful, in a static setting, the refetching of data occurs on every route change. Persistence would be a big stride to decentralizing from larger frameworks further strengthening the use of mini frameworks like Alpine.js.

**Comment by ryangjchandler** [comment]
@jeremyswann - I'll keep it in mind. I want to keep Spruce as light as possible, hence why I'm also removing the event-bus in v2 (since that adds about 1kb to the final build).

**Comment by ryangjchandler** [comment]
@jeremyswann - I merged in some changes that adds support for persistence. I'll be releasing version 2 of Spruce very soon, so keep an eye out for that. In the meantime, you can use the master branch in your project.

**Comment by jeremyswann** [comment]
Thanks @ryangjchandler I'll give it a whirl.
