### ISSUE TITLE
`Spruce.on` does not get the event object

### ISSUE THREAD

**Issue by yaquawa** [ryangjchandler/spruce#56]
Looks like `Spruce.on` does not get the event object just like `@spruce:event-name.window` can do.
Is this a bug or intended?

**Comment by ryangjchandler** [comment]
@yaquawa `Spruce.on` doesn't run through the browser event API, it's a separate event bus and therefore won't receive the events object.

**Comment by yaquawa** [comment]
What do you mean by "browser event API" ?
Could you explain me what's the difference and why they should be separated ?
I can't find more useful info on the readme.
Thanks.

**Comment by ryangjchandler** [comment]
@yaquawa - When `Spruce.emit` is called, 2 different things happen.

Firstly, any listeners registered via `Spruce.on` will be called and passed event-related data. A second part is a browser event that is being dispatched.

By browser event, I mean something that can be listened to using `addEventListener`. The data that was passed to the callback through `Spruce.on` will actually be added to the `$event.detail` property.

Other than that, the event doesn't contain any extra information so I can't see any reason why you would want it in the `Spruce.on` callback.

The event bus has been removed in v2 as well, so I won't be adding any new features as part of v1.

**Comment by yaquawa** [comment]
I got 3 questions now

1. ***`@spruce:event` is totally different thing from `window.spruce.on` ?***

2. ***Will `window.spruce.on` be removed in the future? (Vue3 is going to remove the `vm.$on`)***

3. ***How to emit an event inside the component?***
I tried this, but it failed with error saying $emit is not exists.
```html
<div x-data @spruce:foobar="console.log($event.detail)" x-on:click="$emit('foobar','data')">click me</div>
```



> Other than that, the event doesn't contain any extra information so I can't see any reason why you would want it in the Spruce.on callback.

yes I want to make cross components messagings.

**Comment by ryangjchandler** [comment]
> @ryangjchandler
> I got 3 questions now
> 
>     1. _**`@spruce:event` is totally different thing from `window.spruce.on` ?**_
> 
>     2. _**Will `window.spruce.on` be removed in the future? (Vue3 is going to remove the `vm.$on`)**_
> 
>     3. _**How to emit an event inside the component?**_
>        I tried this, but it failed with error saying `$emit` not exists.
> 
> 
> ```
> <div x-data @spruce:foobar="console.log($event.detail)" x-on:click="$emit('foobar','data')">click me</div>
> ```
> 
> > Other than that, the event doesn't contain any extra information so I can't see any reason why you would want it in the Spruce.on callback.
> 
> yes I want to make cross components messagings.
> I'd like to think of spruce as Vuex, not the Vue itself... So I think event bus is good to have in spruce.

1. `@spruce:event` is totally different yes. When you do `@spruce:event` you are registering an event listener, basically `window.addEventListener('spruce:event')`. When you call `Spruce.on`, you are registering an event listener **with Spruce**, not the `window`.

2. `Spruce.on` will be removed in the future yeah. I'm planning on releasing v2 of Spruce at the end of this month and it will be removed.

3. Inside of your component, you will need to call `Spruce.emit('foobar', { data }`. The second argument must be an object.

**Comment by yaquawa** [comment]
@ryangjchandler Thanks for replying!

> Inside of your component, you will need to call Spruce.emit('foobar', { data }. The second argument must be an object.

I tried this, but nothing happened. what's wrong with my code here?
```html
<div x-data @spruce:foobar="console.log($event.detail)" x-on:click="spruce.emit('foobar',{data:'foo'})">click me</div>
```

**Comment by ryangjchandler** [comment]
You need to add the `.window` modifier and use `Spruce` instead of `spruce`.

**Comment by yaquawa** [comment]
@ryangjchandler Is there any difference between `@spruce:eventname` and `@spruce:eventname.window`? 
I mean should I always add the `.window` in the end of event name?

**Comment by ryangjchandler** [comment]
@yaquawa - using `.window` at the end will register the event listener on the `window` object, which is where Spruce dispatches the events.

`window.Spruce` is definitely the correct syntax, as you can see here: https://github.com/ryangjchandler/spruce/blob/061be1a412d84b174a4695f982f44c605cf18015/src/index.js#L94
