### ISSUE TITLE
storing an object in a store property doesn't work

### ISSUE THREAD

**Issue by Yahav** [ryangjchandler/spruce#60]
So i have the following store:
```
Spruce.store('server', {
  state: 'unloaded', // 'unloaded', 'loading', 'loaded', 'error'
  data: {

  }
})
```

and i'm making request to an API and receiving json which is converted to an object, i want to store this object as is at the store so i do:

`export const accountStore = () =>{ return Spruce.store('account'); }
`
```
accountStore().state = 'loaded';
accountStore().data = response;
```

However this doesn't to work, the state is stored perfectly but the data object doesn't. 
When i console.log the  i get an empty proxy:

```
Proxy {}
[[Handler]]: Object
set: ƒ (t,i,o)
arguments: (...)
caller: (...)
length: 3
name: "set"
prototype: {constructor: ƒ}
__proto__: ƒ ()
[[FunctionLocation]]: js-admin.js?ver=1.0.0:600
[[Scopes]]: Scopes[3]
__proto__: Object
[[Target]]: Object
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
[[IsRevoked]]: false
```

**Comment by ryangjchandler** [comment]
@Yahav Are you able to reproduce this inside of a CodePen or something similar? Makes it a bit easier for me to debug and find the problem (if there is one).

Also, when you `console.log()` the `data` key, it will show as a Proxy since this is what allows deep-reactivity inside of stores / objects. Have you tried accessing a key inside of `data` to see if it's available?

**Comment by Yahav** [comment]
Sorry about that, turns out this is completely my fault.
I was inspecting the store data object inside a Spruce.watch for 'account.state'.
Problem was that i set the state before i set the data object and so when i logged the stored data inside the watch function it was still empty.

**Comment by ryangjchandler** [comment]
Okay, no worries. Glad you figured it out :)
