### ISSUE TITLE
Watch loop bug

### ISSUE THREAD

**Issue by Yahav** [ryangjchandler/spruce#61]
It seem like there's a watch loop bug in which when we set **another store property** inside a watch function it will cause an infinite loop within the first watch.
Now, i'll understand a loop if the property we update is the one in whose watch function we are setting but this is not the situation here.
I've made a quick codepen to demonstrate:
https://codepen.io/yahavIL/pen/ExKzEMM

(notice that the server.state watch never gets called btw)

**Comment by Yahav** [comment]
Same when using events:
https://codepen.io/yahavIL/pen/BaKexLm

**Comment by fredcarle** [comment]
Not sure if it's related but there is also an infinite loop occurring when updating a property to an array.

**Comment by fredcarle** [comment]
Ignore that last comment. It was related to my HTML.

**Comment by ryangjchandler** [comment]
@Yahav I probably won't be looking into this since I'm removing watchers in v2 of Spruce (which will be released very soon). Instead, I'll be documenting a way of using Alpine's own `$watch` with Spruce.

**Comment by Yahav** [comment]
So there will be no way of watching outside of alpine's components?

**Comment by ryangjchandler** [comment]
@Yahav Nope, not in Spruce. The event bus portion of Spruce is the heaviest part of the library and it the most underused. To be honest, I think it was a bit out-of-scope for the initial release. I don't actually use the functionality myself either, so unless enough people are angry about it being dropped, I won't be keeping it in.

**Comment by Yahav** [comment]
I'm not sure what the event bus has to do with it, granted, the events mechanism is quite not useful however, a watch method most definitely is.
**You can't have a state management library without the capability to watch for state changes.**
And yes, you might say Spruce is a state management specifically for Alpine.js and so you could only watch for state changes inside an Alpine.js component however this is just wrong, consider this:
Alpine.js suppose to be a utility, not an entire framework, this is one of the reasons lots of us choose it, you can utilize it as needed but you don't have to base your entire app on it like with vue or react.
and so in my case alpine.js is about 60% of the client-side of the app, but the other 40% still utilize the Spruce and is heavily invested in watch capabilities outside of Alpine.js scope.

I'm sure this is the situation for many Spruce users whether or not they have yet to realize you are about to deprecate the watch mechanism. 

I strongly urge you to reconsider your decision on that matter.

**Comment by ryangjchandler** [comment]
I'll temporarily re-open this. For what it's worth, Spruce has never been marketed as a general-use state management library. It is designed to work with Alpine directly, so anybody who is not using it that way will probably run into bugs and problems and also find that they're grokking the library, using it in unintended ways.

I'm also not willing to maintain something that I don't use myself or something that doesn't have much use anyway. I have thought about having the event bus as a separate library for those who want to use it, or if you wish to continue using it, use the `v1.x` branch of Spruce and don't upgrade.

**Comment by ryangjchandler** [comment]
Fixed in https://github.com/ryangjchandler/spruce/commit/61737952111a7348f483471cabde57d77c53e153

**Comment by Yahav** [comment]
Wait, does that means that you kept the watch functionality at 2.x ?

**Comment by ryangjchandler** [comment]
@Yahav I've decided to keep them, yes. I am currently working on some better documentation for Spruce so will update it to use the new Alpine-included way of watching store changes too.
