### ISSUE TITLE
[Feature Request] Storing data in `localStorage` and `sessionStorage`

### ISSUE THREAD

**Issue by muzafferdede** [ryangjchandler/spruce#7]
Hi Ryan and everyone, 

I was wondering around the package and i got some thoughts as:

Somehow storing data in the `localStorage` or `sessionStorage` and using it via getters and setters. I think code will explain itself. 

```html
<div x-data="{}" x-subscribe>
// retrieves data from `sessionStorage` using  'name'  as key (default driver). 
// Once tab is closed, data will be gone
    <span x-text="$store.application.name"></span>

// retrieves data from `localStorage` using key as 'name'
// Even browser is closed, data will stay
    <span x-text="$store.local.application.name"></span>

</div>
```
using in JS as
```js
Spruce.store('application', { // default to session driver
    name: 'Amazing Alpine Application'
})

Spruce.store('application','local', {
    name: 'Amazing Alpine Application'
})
```
I hope i could described it clear. It's open to discussion and will be great to hear what you guys think. 

Cheers.

**Comment by HugoDF** [comment]
Might be worth allowing an extension point that intercepts updates to the store?

**Comment by muzafferdede** [comment]
I am not sure how the `reactivity` stays during application is live. But i think there might be a way to define `driver` as storage point. Where could we store the data? `memory`, localStorage`, `sessionSorage` if i am not wrong? and maybe some way to use multiple driver. ideas ideas ideas... :)

**Comment by HugoDF** [comment]
Hmmm I would make it more simple, something like an "on change" hook, it's then up to the developer to put wherever they want.

You can already load from local storage btw

**Comment by ryangjchandler** [comment]
As @HugoDF said, you could load from local storage if you wanted too. It would be down to you to save it back at some point.

I have got events on the list to do for v1 too btw.

**Comment by HugoDF** [comment]
Events or hooks?

**Comment by muzafferdede** [comment]
So you mean initial check should be done by developer? E.g. if `$store.application.language.language` is set in the `localStorage`, grab it, if not, set it as: `$store.application.language = 'en'`it. ??

**Comment by ryangjchandler** [comment]
Well, you could do it that way. You could also stringify your entire store object and the put in local storage.

**Comment by ryangjchandler** [comment]
> Events or hooks?

Yeah, hooks not events 😅

**Comment by ryangjchandler** [comment]
Created a new issue #12 for these bits.
