### ISSUE TITLE
Spruce and Laravel Livewire

### ISSUE THREAD

**Issue by Butochnikov** [ryangjchandler/spruce#73]
Spruce not work together with Laravel Livewire, because Alpine waits for Livewire to load first.

in script Livewire:
```
/* Make Alpine wait until Livewire is finished rendering to do its thing. */
    window.deferLoadingAlpine = function (callback) {
        window.addEventListener('livewire:load', function () {
            callback();
        });
    };
```

**Comment by RJFares** [comment]
I was about to write the same issue :)
Following the examples I'm unable to get it to work with Livewire, EXCEPT in the following sequence:

```
        <script src="https://cdn.jsdelivr.net/npm/@ryangjchandler/spruce@2.x.x/dist/spruce.umd.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
        @livewireScripts
```
The above sequence was the only way to get it to work, yet of course, I will get a notification saying
`Livewire: It looks like AlpineJS has already been loaded. Make sure Livewire's scripts are loaded before Alpine.`

If I load it in what I assume should be the correct sequence, I get a "$store is not defined":
```
@livewireScripts
        <script src="https://cdn.jsdelivr.net/npm/@ryangjchandler/spruce@2.x.x/dist/spruce.umd.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
```

Same happens if I load them up through NPM and init in app.js

**Comment by ryangjchandler** [comment]
There are no promises of Spruce working with Livewire, but as a Livewire user myself, I will investigate and see what's happening. 

I've got a feeling that Spruce isn't seeing Livewire's existing `deferLoadingAlpine` callback, despite the fact that it does check for it on https://github.com/ryangjchandler/spruce/blob/29fa962c9c43f0d292845d6364098f16ad6691f1/src/index.js#L140

Looking at this now though, I don't think Spruce needs to defer Alpine at all & can just assign this outside of the callback. This bit of code is legacy and was used to run DOM manipulations _before_ Alpine tries to init.

**Comment by mrahmadt** [comment]
Any workaround to get it work without this annoying message 
" Livewire: It looks like AlpineJS has already been loaded. Make sure Livewire's scripts are loaded before Alpine."

**Comment by ryangjchandler** [comment]
Hey all, I've just pushed to `2.x` a change that removes **Spruce's deferring logic**.

The correct order of the `<script>` tags should be:

```blade
@livewireScripts
<!-- Spruce here -->
<!-- Alpine here -->
```

Best to put this at the end of your `<body>`, as Livewire suggests. I can't reproduce any of the errors, but it's also worth making sure you've got the latest Livewire assets too:

```
php artisan livewire:publish --assets
```

Use the `<script>` tag below to test out my latest changes on `2.x`:

```html
<script src="https://cdn.jsdelivr.net/gh/ryangjchandler/spruce@45fb75dc2a5aee871f49cc91fd524c39697eb95b/dist/spruce.umd.js">
```

**Comment by Butochnikov** [comment]
i tried but ...

```
   @livewireScripts
    <script src="https://cdn.jsdelivr.net/gh/ryangjchandler/spruce@45fb75dc2a5aee871f49cc91fd524c39697eb95b/dist/spruce.umd.js">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js"></script>
</body>
```

Browser Error: 
```
Uncaught (in promise) Error: [Spruce] You must be using Alpine >= 2.5.0 to use Spruce.
    attach index.js:45
    start index.js:18
    promise callback*start utils.js:8
    <anonymous> index.js:139
    <anonymous> spruce.umd.js:1
    <anonymous> spruce.umd.js:1
index.js:45:18
```

**Comment by Butochnikov** [comment]
@ryangjchandler 

work only when this order
```
<script src="https://cdn.jsdelivr.net/gh/ryangjchandler/spruce@45fb75dc2a5aee871f49cc91fd524c39697eb95b/dist/spruce.umd.js"></script>
@livewireScripts
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" d></script>
```

**Comment by ryangjchandler** [comment]
> @ryangjchandler
> 
> work only when this order
> 
> ```
> <script src="https://cdn.jsdelivr.net/gh/ryangjchandler/spruce@45fb75dc2a5aee871f49cc91fd524c39697eb95b/dist/spruce.umd.js"></script>
> @livewireScripts
> <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" d></script>
> ```

What errors are in the console if you use the order I suggested?

**Comment by ryangjchandler** [comment]
@Butochnikov, can you please update Spruce to v2.1.0 and try again please. Spruce should be loaded **after** Livewire:

```blade
@livewireScripts
<!-- Spruce -->
<!-- Alpine -->
```

Or, alternatively, try and place Alpine in the `<head>` with a `defer` attribute.

**Comment by Butochnikov** [comment]
@ryangjchandler 
works great, thanks
