### ISSUE TITLE
Spruce.reset with throw an error if store not defined

### ISSUE THREAD

**Issue by mrahmadt** [ryangjchandler/spruce#75]
Hello

Spruce.reset with throw an error if store not defined, I think it's better to check if the store is not defined, spruce should define it.

because of this issue I have to create my code like this

        if(window.Spruce.store('market') == undefined){
            window.Spruce.store('market', {
                currentDate: currentDate,
            });
        }else{
            window.Spruce.reset('market', {
                currentDate: currentDate,
            });
        }

**Comment by ryangjchandler** [comment]
`Spruce.reset` will just overwrite the key inside of `Spruce.stores`. What error are you getting?

**Comment by ryangjchandler** [comment]
This issue has been silent for a few days so I'm going to close. @mrahmadt Please re-open with some more detailed information on the errors you are receiving.
