### ISSUE TITLE
Persisted store not working with single values

### ISSUE THREAD

**Issue by shiftgeist** [ryangjchandler/spruce#81]
Environment

- alpinejs@2.7.3
- @ryangjchandler/spruce@2.2.1
- codesandbox.io

Example

```js
Spruce.store("colorScheme", "light", true);
```

Simple Reproduction

1. Open https://w4luh.csb.app/ (Source: https://codesandbox.io/s/infallible-waterfall-w4luh)
2. Press one of the buttons
3. Reload page

What happend

(output in html with `[x-text="JSON.stringify($store.colorScheme)"]`)

```html
{"0":"l","1":"i","2":"g","3":"h","4":"t"}
```

Expected

```html
"light"
```

## Workaround

```diff
- Spruce.store("colorScheme", "light", true);
+ Spruce.store("colorScheme", { mode: "light" }, true);
```

**Comment by ryangjchandler** [comment]
@shiftgeist Fixed in #82. Please upgrade to https://github.com/ryangjchandler/spruce/releases/tag/v2.2.2
