### ISSUE TITLE
Docs clarification about order of inclusion of Spruce & Alpine when using NPM/Yarn

### ISSUE THREAD

**Issue by johndwells** [ryangjchandler/spruce#83]
I have just set up Spruce 2.2.2 with Alpine 2.7.3, and contrary to what is stated in the docs, I had to include AlpineJS _before_ Spruce, otherwise Spruce threw a JS error saying that it required Alpine 2.5+ to run.

The Installation instructions mention this note:

> Spruce must be included **before** Alpine to ensure it is initialised before Alpine.

Curiously I have another project running Spruce 2.0.1 with Alpine 2.7.3, and that project is set up as the docs indicate, with Spruce included before Alpine. So I was surprised that when spinning up this new project with 2.2.2, the same code errorred out - especially curious considering 2.0.1 was the version that introduced this version requirement check.

I don't know if the docs have it wrong, or if I've done something wrong, so hoping for some clarity. :)

Thank you for creating Spruce, it's a fantastic addition to the Alpine toolbox!

**Comment by ryangjchandler** [comment]
Hey @johndwells, thanks for reporting. I'll have to take a look this weekend and clarify everything. 

I think most people use the CDN which is probably why this problem hasn't shown up before.

Will update this issue with any information / findings.

**Comment by Pixney-William** [comment]
Personally i had to include Spruce before, or it threw `Alpine Error: "ReferenceError: $store is not defined"`
