### ISSUE TITLE
Spruce.store property name

### ISSUE THREAD

**Issue by dmaixner93** [ryangjchandler/spruce#84]
I was unable to find any 'issues' on this topic. Also not really sure if it is an issue or an intentional format.

When storing items in the `store`, one would store an item as...`Spruce.store('taco', {extraCheese: true,})` or `window.Spruce.store('taco', {extraCheese: true,})`

Based on my understanding, to reference the store above, we could to so like... `$store.spruce.taco` OR `window.Spruce.stores.taco`. However the documentation says to access the item via the 'window' as `window.Spruce.store.taco`. The difference is referring to `stores` rather than `store` in the documentation.

<img width="301" alt="Screen Shot 2020-12-08 at 1 01 24 PM" src="https://user-images.githubusercontent.com/43049828/101529159-d09ebf00-3955-11eb-9f6d-6e7725d7ee98.png">

I could be implementing something incorrectly or it could be a typo in the docs? I suspect the former is the reason since I could not find an 'issue' on this?

Thanks!

**Comment by ryangjchandler** [comment]
@dmaixner93 Thanks for opening up an issue, I'll help you out.

You have created a store as such:

```js
Spruce.store('taco', {
    extraCheese: true
})
```

To access this store **inside** of an Alpine component, you can use the `$store` magic property. You would access the `extraCheese` variable by doing `$store.taco.extraCheese`.

`$store` acts as a shorthand for `window.Spruce.stores` essentially (there's some extra stuff needed).

Outside of Alpine, you would need to use `window.Spruce.store()` as a method, **not** an object. So to get `extraCheese`, you need to call `window.Spruce.store('taco').extraCheese`.

**Comment by dmaixner93** [comment]
Okay, that all makes sense.

I now see calling `window.Spruce.store` in the console returns a function. I should have pondered a little longer I guess 😅

Thank you for your answer.
