### ISSUE TITLE
Array methods is not reactivity

### ISSUE THREAD

**Issue by Sated** [ryangjchandler/spruce#87]
Hello. Array methods like pop, push, splice don't call watchers. Is this normal watcher behavior? In theory, if we use a proxy, we can call a callback to change the array

**Comment by ryangjchandler** [comment]
@Sated Which version of Spruce are you using?

**Comment by Sated** [comment]
> @Sated Which version of Spruce are you using?

I am using spruce@2.2.2. I made a small pen, the watcher is defined on line :37
https://codepen.io/Sated/pen/JjRWNWE?editors=1111

**Comment by ryangjchandler** [comment]
I'll get a fix for this out soon in a 2.3.0 release. Got a couple of others things to deal with before.
