### ISSUE TITLE
Can't get hooks to work

### ISSUE THREAD

**Issue by brennaveen** [ryangjchandler/spruce#88]
Hi, I noticed you added two hooks to Spruce, but they aren't working for me. I've copied and paste the example exactly has you have listed in your documentation.  I don't get any errors, but the functions do not execute.

```
Spruce.starting(function () {
    console.log('Spruce is starting...')
})
```

```
Spruce.started(function () {
    console.log('I can access Proxy instances here...')
})
```

I've verified that I am on the latest version.  Is there anything else I need to do to get these hooks working?

**Comment by ryangjchandler** [comment]
No, you shouldn't need to do anything else. Can you reproduce the issue on CodePen?

I've got a couple of tests that pass and verify that this functionality works correctly..

**Comment by brennaveen** [comment]
Sure

https://codepen.io/blcveen/pen/oNzZLLP

**Comment by ryangjchandler** [comment]
If you see this file https://github.com/ryangjchandler/spruce/blob/2.x/examples/index.html, the `starting` and `started` callbacks run correctly and log to the console.

**Comment by ryangjchandler** [comment]
That CodePen didn't seem to have Alpine so Spruce wouldn't have started up. I've forked it here and it's working: https://codepen.io/ryangjchandler/pen/abmJZyG

Alpine is in the `<head>` and being deferred. Spruce is then at the end of the `<body>` along with the JS panel.

**Comment by brennaveen** [comment]
Ok, in that case I must be causing the problem.  I'm bundling all of my third party javascript assets into one file, then adding the script tag for the file right above the ending body tag.  Thanks for your help.  I'll try to figure how how to handle this.

**Comment by brennaveen** [comment]
In case someone else runs across this issue...

I changed my build have a vendor.js (includes Spruce) and a vendor-deferred.js (includes Alpine), then added vendor-deferred.js in the head and all my other scripts right before the body tag

```
<head>
    <script src="/assets/scripts/vendor-deferred.js" defer></script>
</head>
```

```
<body>
    <script src="/assets/scripts/vendor.js"></script>
    <script src="/assets/scripts/app.js"></script>
</body>
```
