### ISSUE TITLE
Watching changes in nested properties

### ISSUE THREAD

**Issue by bep** [ryangjchandler/spruce#93]
I assume this is by design, but I'm throwing it out there:

Currently, this works fine:

```js
Spruce.store('data', { a: 'value' });
Spruce.watch('data.a', function(value) {
	console.log('Spruce watch', value);
});

Spruce.started(function() {
   Spruce.store('data').a = 'changed';
});
```

But this does not:

```js
Spruce.store('data', { a: 'value' });
Spruce.watch('data', function(value) {
	console.log('Spruce watch', value);
});

Spruce.started(function() {
   Spruce.store('data').a = 'changed';
});
```

**Comment by ryangjchandler** [comment]
Yeah that's correct. I'm planning on adding in support for watching entire objects, it just requires some reworking of the internals. 

Might work on this on a livestream later on today tbh.

**Comment by ryangjchandler** [comment]
@bep Would you expect to receive the key of the prop changed in the callback?

**Comment by bep** [comment]
>Would you expect to receive the key of the prop changed in the callback?

No (that would possibly be useful in some situations, but I think that could be done by setting up multiple watchers)).

**Comment by ryangjchandler** [comment]
@bep This is now available with v2.4.0.

**Comment by bep** [comment]
That was fast! Much appreciated.

**Comment by ryangjchandler** [comment]
@bep I already had an implementation in mind so it wasn't too difficult. Re-open this issue if you find any problems with it.
